[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.dev"

[deploy]
startCommand = "bun --smol dist/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
